[theme]
primaryColor = "#41A928"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F4F8"
textColor = "#1A2B3C"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
